project_name: "Technology Backlog"
default_status: "To Do"
statuses: ["To Do", "In Progress", "Done"]
labels: []
date_format: yyyy-mm-dd hh:mm
max_column_width: 20
default_editor: "rider"
auto_open_browser: false
default_port: 6420
remote_operations: true
auto_commit: false
bypass_git_hooks: false
check_active_branches: true
active_branch_days: 10
task_prefix: "back"
